### PR TITLE
User becomes a mentee

### PR DESCRIPTION
**Pull request by andela-sadefila**
User becomes a Mentee (Step 1). Always merge feature branch with dev.

### CODE REVIEW

**Comment by andela-calim** [comment]
When user becomes a mentor, start time and end time are no longer available (shows `nil`)
screen shot 2015-10-15 at 1 22 35 pm

Searching for Mentor by Start Time doesn't show any result

Searching by Duration gives erroneous result. Gives me a result only when I select `up to 1 day`, even though the duration I chose was less than 10minutes.

**Comment by andela-sadefila** [comment]
@andela-calim look at the roles that were returned. there are two. one is `member` the other is `mentor`. start and end time are available on those

**Comment by andela-sadefila** [comment]
is this fixed now?

**Comment by andela-calim** [comment]
Yes, that has been fixed
I noticed something though. There's the start time and there's the duration. 

For Start Time, a user can search for mentors based on the time the mentorship would start. Meaning, users can search for mentorships that starts in less than 15mins time, between 15 - 30mins time, in 1hour time (say between 30mins to 1hour), in 2 hours time (say between 1hour to 2 hours). That currently doesn't seem to be passing...

Case Scenario: Assuming I become a mentor starting now and lasting for 1 hour. Someone searching under Start Time, selecting < 15mins should show my name. Other options shouldn't show my name.

**Comment by andela-calim** [comment]
@andela-sadefila 
For Duration...
Case Scenario: For mentorship lasting 1 hour, Selecting Duration of 1 day still shows the user

**Comment by andela-sadefila** [comment]
right now, it is not "between" time slots. as shown, it is "before" time slots. so 15 mins is before next 1 hour. selecting 1 hour will show you available as well.

**Comment by andela-calim** [comment]
Are you referring to the Start Time?

**Comment by andela-sadefila** [comment]
yeah

**Comment by andela-sadefila** [comment]
and for mentorship, it is the other way round
 
a mentor that has 1 day set will appear when you search for one hour, because you can still make use of him. he is free for one day and you are booking one hour. so?

**Comment by andela-calim** [comment]
Ok, so for start time, Once the mentorship has started, it shouldn't show up at all. 
The options mean mentorships starting in less than 15mins time, mentorships starting in 30 mins time and so on.
Once the mentorship has started, The mentor's name shouldn't show up in start time... or maybe we could have an option for Ongoing, which shows mentorships that have started already (Suggestion).

As regards your last comment, becoming a mentor starting immediately and ending in an hour time, meaning the duration is 1 hour. 
- If I search for mentors with duration of 15mins or 30 mins, the mentor should show. 
- If I search for duration of 1 day, the mentor shouldn't show. Currently, I still see that mentor

**Comment by andela-sadefila** [comment]
I guess you can pull and check now. Hope your thirs is quenched now??? @andela-calim

**Pull request closed without merging**
